{% set data= load_setup_py_data() %}
package:
  name: ts-mthexapod
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  string: "py{{ PY_VER | replace('.', '') }}{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"

test:
  requires:
    - ts-conda-build =0.5
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
    - ts-hexrotcomm
    - ts-simactuators
  source_files:
    - python
    - bin
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{python}}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  build:
    - python {{python}}
    - ts-conda-build =0.5
  run:
    - python {{python}}
    - setuptools
    - setuptools_scm
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
    - ts-hexrotcomm
    - ts-simactuators
    - scipy
